<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Views\AuthView.axaml.cs">
            <DependentUpon>AuthView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
		<Compile Update="Views\BulkDownloadView.axaml.cs">
			<DependentUpon>BulkDownloadView.axaml</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\DownloadsView.axaml.cs">
            <DependentUpon>DownloadsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\DownloadView.axaml.cs">
            <DependentUpon>DownloadView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\InfoView.axaml.cs">
            <DependentUpon>InfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\LoadingView.axaml.cs">
            <DependentUpon>LoadingView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\LogView.axaml.cs">
            <DependentUpon>LogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\PreferencesView.axaml.cs">
            <DependentUpon>PreferencesView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SearchResultView.axaml.cs">
            <DependentUpon>SearchResultView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SearchView.axaml.cs">
            <DependentUpon>SearchView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SubOnlyView.axaml.cs">
            <DependentUpon>SubOnlyView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UpdateInfoView.axaml.cs">
            <DependentUpon>UpdateInfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\WelcomeView.axaml.cs">
            <DependentUpon>WelcomeView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\AuthView.axaml.cs">
            <DependentUpon>AuthView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\DownloadsView.axaml.cs">
            <DependentUpon>DownloadsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\DownloadView.axaml.cs">
            <DependentUpon>DownloadView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\InfoView.axaml.cs">
            <DependentUpon>InfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\LoadingView.axaml.cs">
            <DependentUpon>LoadingView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\LogView.axaml.cs">
            <DependentUpon>LogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MessageBoxWindow.axaml.cs">
            <DependentUpon>MessageBoxWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\PreferencesView.axaml.cs">
            <DependentUpon>PreferencesView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SearchResultView.axaml.cs">
            <DependentUpon>SearchResultView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SearchView.axaml.cs">
            <DependentUpon>SearchView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SubOnlyView.axaml.cs">
            <DependentUpon>SubOnlyView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UpdateInfoView.axaml.cs">
            <DependentUpon>UpdateInfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\WelcomeView.axaml.cs">
            <DependentUpon>WelcomeView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Views\AuthView.axaml" />
		<AdditionalFiles Include="Views\BulkDownloadView.axaml" />
		<AdditionalFiles Include="Views\DownloadsView.axaml" />
        <AdditionalFiles Include="Views\DownloadView.axaml" />
        <AdditionalFiles Include="Views\InfoView.axaml" />
        <AdditionalFiles Include="Views\LoadingView.axaml" />
        <AdditionalFiles Include="Views\LogView.axaml" />
        <AdditionalFiles Include="Views\MainWindow.axaml" />
        <AdditionalFiles Include="Views\PreferencesView.axaml" />
        <AdditionalFiles Include="Views\SearchResultView.axaml" />
        <AdditionalFiles Include="Views\SearchView.axaml" />
        <AdditionalFiles Include="Views\SubOnlyView.axaml" />
        <AdditionalFiles Include="Views\UpdateInfoView.axaml" />
        <AdditionalFiles Include="Views\WelcomeView.axaml" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TwitchLeecher.Core\TwitchLeecher.Core.csproj" />
        <ProjectReference Include="..\TwitchLeecher.Services\TwitchLeecher.Services.csproj" />
        <ProjectReference Include="..\TwitchLeecher.Shared\TwitchLeecher.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.6" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Deadpikle.AvaloniaProgressRing" Version="0.10.10" />
        <PackageReference Include="Projektanker.Icons.Avalonia" Version="9.6.1" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
		<PackageReference Include="Selenium.WebDriver" Version="4.31.0" />
    </ItemGroup>
    <ItemGroup>
        <Resource Include="..\Resources\Images\TL_Icon.png">
            <Link>Resources\TL_Icon.png</Link>
        </Resource>
    </ItemGroup>
    <ItemGroup>
        <Resource Include="..\Resources\Images\TL_Icon.ico">
            <Link>Resources\TL_Icon.ico</Link>
        </Resource>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Assets\" />
    </ItemGroup>
</Project>
